# Generated by Django 5.0.6 on 2024-10-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_post_heading_en_us_post_heading_ru_post_text_en_us_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='category_name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name_en_us',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='category_name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name_ru',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='category_name'),
        ),
        migrations.AlterField(
            model_name='post',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='time of addition'),
        ),
        migrations.AlterField(
            model_name='post',
            name='heading',
            field=models.CharField(max_length=255, verbose_name='heading'),
        ),
        migrations.AlterField(
            model_name='post',
            name='heading_en_us',
            field=models.CharField(max_length=255, null=True, verbose_name='heading'),
        ),
        migrations.AlterField(
            model_name='post',
            name='heading_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='heading'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text_en_us',
            field=models.TextField(null=True, verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='text'),
        ),
    ]
